// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCynI5OayEshv2sItJC__60KD45JYTtyUA',
    appId: '1:845181477025:web:6ad07ad70ad638dc8f10e0',
    messagingSenderId: '845181477025',
    projectId: 'accord-331dc',
    authDomain: 'accord-331dc.firebaseapp.com',
    storageBucket: 'accord-331dc.firebasestorage.app',
    measurementId: 'G-KJQK662FQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpb1b2rpUrtSqBYOh_Y_2SOomZ9PXsNDg',
    appId: '1:845181477025:android:5522b33d27c2fb798f10e0',
    messagingSenderId: '845181477025',
    projectId: 'accord-331dc',
    storageBucket: 'accord-331dc.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA00GUs0XOuo2hF9giPoL6mWealCUFSvI',
    appId: '1:845181477025:ios:e3c5022688fcbb748f10e0',
    messagingSenderId: '845181477025',
    projectId: 'accord-331dc',
    storageBucket: 'accord-331dc.firebasestorage.app',
    iosBundleId: 'com.example.accord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCynI5OayEshv2sItJC__60KD45JYTtyUA',
    appId: '1:845181477025:web:a549a5fc7bda78288f10e0',
    messagingSenderId: '845181477025',
    projectId: 'accord-331dc',
    authDomain: 'accord-331dc.firebaseapp.com',
    storageBucket: 'accord-331dc.firebasestorage.app',
    measurementId: 'G-KFZS5YF1ZZ',
  );
}
